from selenium.webdriver.common.by import By

class LoginPageLocators:
    EMAIL = (By.CSS_SELECTOR, "")
    PASSWORD = (By.CSS_SELECTOR, "")
    SIGN_IN = (By.CSS_SELECTOR, "")
    SIGN_UP = (By.CSS_SELECTOR, "")

class MainPageLocators:
    CHECKBOX1 = (By.CSS_SELECTOR, "")
    CHECKBOX2 = (By.CSS_SELECTOR, "")
    CHECKBOX3 = (By.CSS_SELECTOR, "")
    CHECKBOX_ALL = (By.CSS_SELECTOR, "")
    SEARCH_FIELD = (By.CSS_SELECTOR, "")
    SUBMIT_BTN = (By.CSS_SELECTOR, "")
    CANCEL_BTN = (By.CSS_SELECTOR, "")
    SUCCESS_TOAST = (By.CSS_SELECTOR, "")
    ERROR_TOAST = (By.CSS_SELECTOR, "")
    THUMBNAIL_1 = (By.CSS_SELECTOR, "")
    THUMBNAIL_2 = (By.CSS_SELECTOR, "")
    THUMBNAIL_3 = (By.CSS_SELECTOR, "")
    THUMBNAIL_4 = (By.CSS_SELECTOR, "")
    RADIOBUTTON_1 = (By.CSS_SELECTOR, "")
    RADIOBUTTON_2 = (By.CSS_SELECTOR, "")
    RADIOBUTTON_3 = (By.CSS_SELECTOR, "")
    RADIOBUTTON_4 = (By.CSS_SELECTOR, "")
    FILTER_1 = (By.CSS_SELECTOR, "")
    FILTER_2 = (By.CSS_SELECTOR, "")
    FILTER_3 = (By.CSS_SELECTOR, "")
    FILTER_4 = (By.CSS_SELECTOR, "")
    FIELD_1 = (By.CSS_SELECTOR, "")
    FIELD_2 = (By.CSS_SELECTOR, "")
    FIELD_3 = (By.CSS_SELECTOR, "")

class LeftSidebarLocators:
    L_SIDEBAR_BTN_1 = (By.CSS_SELECTOR, "")
    L_SIDEBAR_BTN_2 = (By.CSS_SELECTOR, "")
    L_SIDEBAR_BTN_3 = (By.CSS_SELECTOR, "")
    L_SIDEBAR_BTN_4 = (By.CSS_SELECTOR, "")
    L_SIDEBAR_BTN_5 = (By.CSS_SELECTOR, "")
    L_SIDEBAR_BTN_6 = (By.CSS_SELECTOR, "")

class RightSidebarLocators:
    R_SIDEBAR_BTN_1 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_2 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_3 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_4 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_5 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_6 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_7 = (By.CSS_SELECTOR, "")
    R_SIDEBAR_BTN_8 = (By.CSS_SELECTOR, "")

